<a href="https://colab.research.google.com/github/E-SaiAnurath/CSBTB29/blob/main/Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Implement Basic Data Structures using Numpy, Pandas
1. Lists
2. Arrays
3. Identify their type using type()
4. Perform mathematical operations on these datasets created - multiplication, division,
5. Combine text with Numpy fuction to generate a textual output - ”Addition of Two:
array1 +array 2
6. Implement np.sin(), log(), log2(), np.exp())


In [ ]:
import numpy as np

In [ ]:
#1D Array
Array_1=np.array([8,9,7,5,6,6])
print(Array_1)
print(type(Array_1))
print("Sum of the given 1D array:",np.sum(Array_1))
print("Mean of the 1D array:",np.mean(Array_1))

[8 9 7 5 6 6]
<class 'numpy.ndarray'>
Sum of the given 1D array: 41
Mean of the 1D array: 6.833333333333333


In [ ]:
#2D array
Array_2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D NumPy Array:\n", Array_2)
print("Element at position (1, 2):", Array_2[1, 2])
print("Sum of all elements:", np.sum(Array_2))
print(type(Array_2))

2D NumPy Array:
 [[1 2 3]
 [4 5 6]]
Element at position (1, 2): 6
Sum of all elements: 21
<class 'numpy.ndarray'>


In [ ]:
#3D array
Array_3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[4,5],[3,2]]])
print(Array_3)
print("Element at position (1, 1, 0):", Array_3[1, 1, 0])
print("Sum of elements in 3D array:", np.sum(Array_3))
print("Shape of 3D array:", Array_3.shape)
print("Type of 3D Array:", type(Array_3))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]

 [[4 5]
  [3 2]]]
Element at position (1, 1, 0): 7
Sum of elements in 3D array: 50
Shape of 3D array: (3, 2, 2)
Type of 3D Array: <class 'numpy.ndarray'>


In [3]:
#4D array
import numpy as np
Array_4 = np.array([[[[4, 6, 5], [3, 4, 5]], [[5, 6, 8], [7, 8, 10]]],
                     [[[9, 10, 15], [11, 12, 14]], [[13, 14, 18], [15, 16, 19]]]])
print("4D Array:\n", Array_4)
print("Type of 4D Array:", type(Array_4))
print("Sum of elements in 4D array:", np.sum(Array_4))
print("Shape of 4D array:", Array_4.shape)

4D Array:
 [[[[ 4  6  5]
   [ 3  4  5]]

  [[ 5  6  8]
   [ 7  8 10]]]


 [[[ 9 10 15]
   [11 12 14]]

  [[13 14 18]
   [15 16 19]]]]
Type of 4D Array: <class 'numpy.ndarray'>
Sum of elements in 4D array: 237
Shape of 4D array: (2, 2, 2, 3)


In [14]:
Array_a = np.array([9, 8, 7])
Array_b = np.array([10, 9, 5])
array_div = Array_b / Array_a
print("Division of Two Arrays:", array_div)
array_add = Array_a + Array_b
print("Addition of Two Arrays:", array_add)
array_mul = Array_a * Array_b
print("Multiplication of Two Arrays:", array_mul)
array_pow = np.power(Array_a, 2)
print("Element-wise Power (array_a^2):", array_pow)


Division of Two Arrays: [1.11111111 1.125      0.71428571]
Addition of Two Arrays: [19 17 12]
Multiplication of Two Arrays: [90 72 35]
Element-wise Power (array_a^2): [81 64 49]


implementing of sin,log

In [13]:
sin_values = np.sin(Array_a)
print("\nSin of Array_1:", sin_values)
log_values = np.log(Array_b)
print("Log of Array_2:", log_values)
log2_values = np.log2(Array_b)
print("Log base-2 of Array_2:", log2_values)
exp_values = np.exp(Array_a)
print("Exponential of Array_1:", exp_values)


Sin of Array_1: [0.41211849 0.98935825 0.6569866 ]
Log of Array_2: [2.30258509 2.19722458 1.60943791]
Log base-2 of Array_2: [3.32192809 3.169925   2.32192809]
Exponential of Array_1: [8103.08392758 2980.95798704 1096.63315843]
