<a href="https://colab.research.google.com/github/e-anurath/CSBTB29/blob/main/arraysort.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Example 1

In [ ]:
import numpy as np
arr = np.array([4,5,6,2])
print(np.sort(arr))

[4 5 6 2]


Example 2

In [6]:

import pandas as pd

# Creating the Series
sr = pd.Series([150, 50, 30, 20, 40, 100])

# Create the Index
items = ['Rice', 'Suger', 'Salt', 'milk Packet', 'curd', 'ThumbsUp']

# set the index
sr.index = items

# Print the series
print(sr)


Rice           150
Suger           50
Salt            30
milk Packet     20
curd            40
ThumbsUp       100
dtype: int64


Example 3


In [7]:
# importing packages
import pandas
import numpy

# create Pandas array with dtype from numpy
pd_arr = pandas.array(data=['1', '2', '3', '4', '5','6'],
					dtype=numpy.int8)

# print the formed array
print(pd_arr)


<NumpyExtensionArray>
[1, 2, 3, 4, 5, 6]
Length: 6, dtype: int8


Example 4

In [10]:
import numpy as np
import pandas as pd
list_2D= [[1, 0 ,1], [0, 1, 0] , [0 , 0 , 1]]
array = np.array(list_2D)
print(array)


[[1 0 1]
 [0 1 0]
 [0 0 1]]
